import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import { FOLLOW_UPS_MARKER } from "./agent/stream";
import type { Session, SessionMeta } from "./types";

export type AgentLine = { sessionId: string; nodeId: string; line: string };

export type AgentExit = {
  sessionId: string;
  nodeId: string;
  success: boolean;
  canceled: boolean;
  error: string | null;
};

export type GenerationRequest = {
  sessionId: string;
  nodeId: string;
  prompt: string;
  /** Model alias for the agent CLI; null inherits the CLI default. */
  model: string | null;
  /** Reasoning effort for the agent CLI; null inherits the CLI default. */
  effort: string | null;
};

export type Ipc = {
  listSessions(): Promise<SessionMeta[]>;
  loadSession(id: string): Promise<Session>;
  saveSession(session: Session): Promise<void>;
  deleteSession(id: string): Promise<void>;
  startGeneration(request: GenerationRequest): Promise<void>;
  cancelGeneration(nodeId: string): Promise<void>;
  onAgentLine(handler: (event: AgentLine) => void): void;
  onAgentExit(handler: (event: AgentExit) => void): void;
};

export const isTauri = "__TAURI_INTERNALS__" in window;

const tauriIpc: Ipc = {
  listSessions: () => invoke("list_sessions"),
  loadSession: (id) => invoke("load_session", { id }),
  saveSession: (session) => invoke("save_session", { session }),
  deleteSession: (id) => invoke("delete_session", { id }),
  startGeneration: (request) => invoke("start_generation", { request }),
  cancelGeneration: (nodeId) => invoke("cancel_generation", { nodeId }),
  onAgentLine: (handler) => {
    void listen<AgentLine>("agent-line", (event) => handler(event.payload));
  },
  onAgentExit: (handler) => {
    void listen<AgentExit>("agent-exit", (event) => handler(event.payload));
  },
};

/**
 * In-memory stand-in used when the frontend runs in a plain browser
 * (`pnpm dev` without Tauri). Lets the whole UI, including streaming, be
 * exercised without the Rust side or the claude CLI.
 */
const createMockIpc = (): Ipc => {
  const sessions = new Map<string, Session>();
  const timers = new Map<string, number>();
  let lineHandler: (event: AgentLine) => void = () => {};
  let exitHandler: (event: AgentExit) => void = () => {};

  const mockAnswer = [
    "This is a **mock answer** streamed by the browser-only development build.",
    "",
    "It exists so the canvas, reading pane, and streaming pipeline can be exercised without the claude CLI. Inline math like $E = mc^2$ works, and so do display equations:",
    "",
    "$$\\text{softmax}(x_i) = \\frac{e^{x_i}}{\\sum_j e^{x_j}}$$",
    "",
    "```python",
    "scores = queries @ keys.T / dim**0.5",
    "weights = softmax(scores)",
    "```",
    "",
    "Real answers are generated by your local `claude` CLI inside the Tauri app.",
    FOLLOW_UPS_MARKER,
    "- What does the attention formula actually compute?",
    "- Why divide by the square root of the dimension?",
    "- How do multiple attention heads differ?",
  ].join("\n");

  return {
    listSessions: () =>
      Promise.resolve(
        [...sessions.values()]
          .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
          .map((session) => ({
            id: session.id,
            question: session.question,
            updatedAt: session.updatedAt,
            nodeCount: session.nodes.length,
          })),
      ),
    loadSession: (id) => {
      const session = sessions.get(id);
      return session
        ? Promise.resolve(structuredClone(session))
        : Promise.reject(new Error(`unknown session ${id}`));
    },
    saveSession: (session) => {
      sessions.set(session.id, structuredClone(session));
      return Promise.resolve();
    },
    deleteSession: (id) => {
      sessions.delete(id);
      return Promise.resolve();
    },
    startGeneration: ({ sessionId, nodeId }) => {
      const chunks = mockAnswer.match(/[^]{1,12}/g) ?? [];
      let index = 0;
      const timer = window.setInterval(() => {
        if (index < chunks.length) {
          const event = {
            type: "stream_event",
            event: {
              type: "content_block_delta",
              delta: { type: "text_delta", text: chunks[index] },
            },
          };
          lineHandler({ sessionId, nodeId, line: JSON.stringify(event) });
          index += 1;
          return;
        }
        window.clearInterval(timer);
        timers.delete(nodeId);
        const result = {
          type: "result",
          subtype: "success",
          is_error: false,
          result: mockAnswer,
        };
        lineHandler({ sessionId, nodeId, line: JSON.stringify(result) });
        exitHandler({ sessionId, nodeId, success: true, canceled: false, error: null });
      }, 24);
      timers.set(nodeId, timer);
      return Promise.resolve();
    },
    cancelGeneration: (nodeId) => {
      const timer = timers.get(nodeId);
      if (timer !== undefined) {
        window.clearInterval(timer);
        timers.delete(nodeId);
        for (const session of sessions.values()) {
          if (session.nodes.some((node) => node.id === nodeId)) {
            exitHandler({
              sessionId: session.id,
              nodeId,
              success: false,
              canceled: true,
              error: null,
            });
          }
        }
      }
      return Promise.resolve();
    },
    onAgentLine: (handler) => {
      lineHandler = handler;
    },
    onAgentExit: (handler) => {
      exitHandler = handler;
    },
  };
};

export const ipc: Ipc = isTauri ? tauriIpc : createMockIpc();
